
spring.application.name=config-client-prod
server.port=8080

vehicle.name={cipher}AQB3YEi6b+Zl8NnFF7R2HEO3s+1mf8dkpUne8yfHRgOkg0EJoG18knelmCwHXtOU/FY2u/4DUhTZl5EcmVE5R9d3DLpmlSPNy1IPaOvO2MjkbOcKkjwF0B+DUSerC0QDhUKH3A+a/i3VpR5Y3v/iAAi5DPh+qY+CXwqsEOn+cN6ZU6uTlB7+kPf0Du3IG0pIZKfP97id+9e7lx9xQfxL7+RI/W4Iozzbc1PIVse00V9JmMWWpkGrSe6dsMU7kgtn01w9qUz6oL4qQ22DyB4QQHVZJ7n+0gI+XIBxwma8tRxFkOrsDKWNCoq6PTLEmjnUKAH98Ue8AqLIJ7grKnNAH8AifehTAOMennzLbJCqZp3f+XTlbmUsY3sN7xNyWECQNsXzEmSuLLgQ/gpo1NDvkymz
vehicle.type=Bike
vehicle.color=White
vehicle.engineType=Petrol
vehicle.tankSize=15L
